stages:
  - build
  - analyze
  - test

lint-job-backend:
  stage: analyze
  image: node:20.12.2
  script:
    - echo "Linting backend code..."
    - npm run lint
    - echo "Linting complete for Backend."

unit-test-job-backend:
  stage: test
  image: node:20.12.2
  script:
    - echo "Running backend unit tests..."
    - npm test
    - echo "Unit test complete for Backend."
