stages:
  - analyze
  - test

before_script:
  - echo "Setting up the environment..."
  - apt-get update -y && apt-get install -y nodejs npm
  - npm install -g npm@latest
  - echo "Environment setup complete."

lint-job-backend:
  stage: analyze
  script:
    - echo "Linting backend code..."
    - cd backend
    - npm install
    - npm run lint
    - echo "Linting complete for Backend."

unit-test-job-backend:
  stage: test
  script:
    - echo "Running backend unit tests..."
    - cd backend
    - npm install
    - npm test
    - echo "Unit test complete for Backend."
