stages:
  - analyze
  - test

lint-job-backend:
  stage: analyze
  script:
    - echo "Linting backend code..."
    - npm run lint
    - echo "Linting complete for Backend."

unit-test-job-backend:
  stage: test
  script:
    - echo "Running backend unit tests..."
    - npm test
    - echo "Unit test complete for Backend."
