name: Software Development CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend_lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Backend lint
        working-directory: backend
        run: npm install && npm run lint

  frontend_lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Frontend lint
        working-directory: frontend
        run: npm install && npm run lint

  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: backend_lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Backend test
        working-directory: backend
        run: npm install && npm run test

  frontend_tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: frontend_lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Frontend tests with Cypress
        working-directory: frontend
        run: npm install && npx cypress run
