name: Software Development CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Backend lint and test
        working-directory: backend
        run: |
          npm install
          npm run lint -- --ignore-path .gitignore --ignore dist
          npm run test

  frontend_tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Frontend tests with Cypress
        working-directory: frontend
        run: |
          npm install
          npx run cypress run

