name: Software Development CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Frontend and Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Build Backend
      - name: Build Backend
        working-directory: backend
        run: npm install && npm run build

      # Build Frontend
      - name: Build Frontend
        working-directory: frontend
        run: npm install && npm run build

  analyze:
    name: Analyze (Lint) Backend and Frontend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Backend linting
      - name: Backend lint
        working-directory: backend
        run: npm run lint

      # Frontend linting
      - name: Frontend lint
        working-directory: frontend
        run: npm run lint

  test:
    name: Test Backend and Frontend
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Backend tests
      - name: Backend test
        working-directory: backend
        run: npm run test

      # Frontend tests with Cypress
      - name: Frontend tests with Cypress
        working-directory: frontend
        run: npm install && npx cypress run
