name: Software Development CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend_build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Build Backend
        working-directory: backend
        run: npm run build

  frontend_build:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

  backend_lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    needs: [backend_build, frontend_build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js for Backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Backend linting
      - name: Backend lint
        working-directory: backend
        run: npm install && npm run lint

  frontend_lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    needs: [backend_build, frontend_build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js for Frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Frontend linting
      - name: Frontend lint
        working-directory: frontend
        run: npm install && npm run lint

  backend_test:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: [backend_lint, frontend_lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js for Backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Backend tests
      - name: Backend test
        working-directory: backend
        run: npm install && npm run test

  frontend_test:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: [backend_lint, frontend_lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js for Frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Frontend tests with Cypress
      - name: Frontend tests with Cypress
        working-directory: frontend
        run: npm install && npx cypress run
