name: Software Development CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Build Stage
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Build Backend
        working-directory: backend
        run: npm run build

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

  # Analyze Stage
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Backend linting
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Backend lint
        working-directory: backend
        run: npm install && npm run lint

      # Frontend linting
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Frontend lint
        working-directory: frontend
        run: npm install && npm run lint

  # Test Stage
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Backend tests
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Backend test
        working-directory: backend
        run: npm install && npm run test

      # Frontend tests with Cypress
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Frontend tests with Cypress
        working-directory: frontend
        run: npm install && npx cypress run
